# Generated by Django 4.2.14 on 2024-08-06 15:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phase', models.IntegerField(choices=[(1, 'BRP'), (2, 'BPN'), (2, 'BHA')])),
                ('flat_occupancy', models.IntegerField(choices=[(1, 'Bachelors'), (2, 'Family')])),
                ('unit_id', models.IntegerField()),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('emergency_number', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('adhar_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rent_and_maintenance', models.FloatField()),
                ('parking', models.FloatField()),
                ('other_payments', models.FloatField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('furnished', models.BooleanField(default=True)),
                ('internet', models.BooleanField(default=True)),
                ('internet_charge', models.FloatField(blank=True)),
                ('security_deposit', models.IntegerField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('agreement', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('adhar', models.FileField(blank=True, null=True, upload_to='adhars/')),
            ],
        ),
    ]
