# Generated by Django 4.2.14 on 2024-08-06 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_and_maintance_paid', models.FloatField(blank=True)),
                ('parking_paid', models.FloatField(blank=True)),
                ('internet_paid', models.FloatField(blank=True)),
                ('water_to_be_paid', models.FloatField(blank=True)),
                ('water_paid', models.FloatField(blank=True)),
                ('other_paid', models.FloatField(blank=True)),
                ('transaction_id', models.IntegerField(blank=True)),
                ('payment_type', models.IntegerField(choices=[(1, 'Bank'), (2, 'Cash'), (2, 'Other')], default=1)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('date_entered', models.DateField(default=datetime.date.today)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentApp.apartment')),
            ],
        ),
    ]
