# Generated by Django 4.2.14 on 2024-08-06 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentApp', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='adhar_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='emergency_number',
            field=models.BigIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='internet_charge',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='other_payments',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='parking',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='phase',
            field=models.IntegerField(choices=[(1, 'BRP'), (2, 'BPN'), (3, 'BHA')]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='phone_number',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rent_and_maintenance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='security_deposit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='unit_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='internet_paid',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='other_paid',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='parking_paid',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Bank'), (2, 'Cash'), (3, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rent_and_maintance_paid',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='water_paid',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='water_to_be_paid',
            field=models.BigIntegerField(blank=True),
        ),
    ]
