# Generated by Django 4.2.23 on 2025-06-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentApp', '0003_alter_apartment_adhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='emergency_number',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='phase',
            field=models.IntegerField(choices=[(1, 'BRP'), (2, 'BPN'), (3, 'BHA'), (4, 'Office'), (5, 'Shop')]),
        ),
    ]
