# Generated by Django 4.2.23 on 2025-06-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentApp', '0004_alter_apartment_emergency_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='phase',
            field=models.IntegerField(choices=[(1, 'BRN'), (2, 'BPN'), (3, 'BHIG'), (4, 'Office'), (5, 'Shop')]),
        ),
    ]
