# Generated by Django 4.2.23 on 2025-06-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentApp', '0005_alter_apartment_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='phase',
            field=models.IntegerField(choices=[(1, 'BRP'), (2, 'BRN'), (3, 'BHIG'), (4, 'Office'), (5, 'Shop')]),
        ),
    ]
