# Generated by Django 4.2.23 on 2025-06-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentApp', '0006_alter_apartment_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='internet',
            field=models.BooleanField(default=False),
        ),
    ]
