# Generated by Django 4.2.23 on 2025-06-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentApp', '0007_alter_apartment_internet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='flat_occupancy',
            field=models.IntegerField(choices=[(1, 'Bachelors'), (2, 'Family'), (3, 'N/A')]),
        ),
    ]
