# Generated by Django 4.2.23 on 2025-06-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentApp', '0008_alter_apartment_flat_occupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='flat_occupancy',
            field=models.IntegerField(choices=[(1, 'Bachelors'), (2, 'Family'), (3, 'Office'), (4, 'Shop'), (5, 'N/A')]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='phase',
            field=models.IntegerField(choices=[(1, 'BRP'), (2, 'BRN'), (3, 'BHIG')]),
        ),
    ]
